datasets:
  - name: "A24"
    h5_path: "./datasets/neutral/others/A24.h5"
  - name: "charge_transfer"
    h5_path: "./datasets/neutral/others/charge_transfer.h5"
  - name: "DES370K-MACEOFF23-elements"
    h5_path: "./datasets/neutral/others/DES370K-MACEOFF23-elements.h5"
  - name: "HB104"
    h5_path: "./datasets/neutral/others/HB104.h5"
  - name: "L7"
    h5_path: "./datasets/neutral/others/L7.h5"
  - name: "NCIA_D442x10-MACEOFF23-elements"
    h5_path: "./datasets/neutral/others/NCIA_D442x10-MACEOFF23-elements.h5"
  - name: "NCIA_HB300SPXx10"
    h5_path: "./datasets/neutral/others/NCIA_HB300SPXx10.h5"
  - name: "NCIA_HB375x10"
    h5_path: "./datasets/neutral/others/NCIA_HB375x10.h5"
  - name: "NCIA_R739x5-MACEOFF23-elements"
    h5_path: "./datasets/neutral/others/NCIA_R739x5-MACEOFF23-elements.h5"
  - name: "NCIA_SH250x10-MACEOFF23-elements"
    h5_path: "./datasets/neutral/others/NCIA_SH250x10-MACEOFF23-elements.h5"
  - name: "R160x6"
    h5_path: "./datasets/neutral/others/R160x6.h5"
  - name: "S12L-MACEOFF23-elements"
    h5_path: "./datasets/neutral/others/S12L-MACEOFF23-elements.h5"
  - name: "S66a8"
    h5_path: "./datasets/neutral/others/S66a8.h5"
  - name: "S66x8"
    h5_path: "./datasets/neutral/others/S66x8.h5"
  - name: "sulfurx8"
    h5_path: "./datasets/neutral/others/sulfurx8.h5"
  - name: "X40x10"
    h5_path: "./datasets/neutral/others/X40x10.h5"
 
models:
  - type: "aimnet2"
    path: "./models/aimnet2/aimnet2_2025_b973c_d3_0.jpt"
  - type: "aimnet2"
    path: "./models/aimnet2/aimnet2_b973c_d3_0.jpt"  
  - type: "aimnet2"
    path: "./models/aimnet2/aimnet2_wb97m_d3_0.jpt"  
  - type: "maceoff"
    path: "./models/maceoff/MACE-OFF23_small.model"
  - type: "maceoff"
    path: "./models/maceoff/MACE-OFF23_medium.model"
  - type: "maceoff"
    path: "./models/maceoff/MACE-OFF23b_medium.model"
  - type: "maceoff"
    path: "./models/maceoff/MACE-OFF23_large.model"
  - type: "maceoff"
    path: "./models/maceoff/MACE-OFF24_medium.model"
  - type: "maceomol"
    path: "./models/maceomol/MACE-omol-0-extra-large-1024.model"
